/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author GABRIELAOLIVEIRAMONT
 */
public class Estoque extends javax.swing.JFrame {

    /**
     * Creates new form Estoque
     */
    public Estoque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblTabelaEstoque = new javax.swing.JLabel();
        LblProdutoEstoque = new javax.swing.JLabel();
        TxtProdutoEstoque = new javax.swing.JTextField();
        LblValorEstoque = new javax.swing.JLabel();
        TxtQuantidadeEstoque = new javax.swing.JTextField();
        LblQuantidadeEstoque = new javax.swing.JLabel();
        TxtValorEstoque1 = new javax.swing.JTextField();
        BtnInserirEstoque = new javax.swing.JButton();
        BtnDeletarEstoque = new javax.swing.JButton();
        BtnAnteriorEstoque = new javax.swing.JButton();
        BtnLimparCamposEstoque3 = new javax.swing.JButton();
        BtnProximoEstoque = new javax.swing.JButton();
        BtnAtualizarEstoque2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Estoque"); // NOI18N
        setResizable(false);

        LblTabelaEstoque.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LblTabelaEstoque.setText("  TABELA ESTOQUE");

        LblProdutoEstoque.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LblProdutoEstoque.setText("Produto :");

        LblValorEstoque.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LblValorEstoque.setText("Valor :");

        LblQuantidadeEstoque.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LblQuantidadeEstoque.setText("Quantidade em Estoque :");

        BtnInserirEstoque.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnInserirEstoque.setText("Inserir");

        BtnDeletarEstoque.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnDeletarEstoque.setText("Deletar");

        BtnAnteriorEstoque.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnAnteriorEstoque.setText("Anterior");

        BtnLimparCamposEstoque3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnLimparCamposEstoque3.setText("Limpar Campos");

        BtnProximoEstoque.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnProximoEstoque.setText("Próximo");

        BtnAtualizarEstoque2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnAtualizarEstoque2.setText("Atualizar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblTabelaEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LblProdutoEstoque)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtProdutoEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LblValorEstoque)
                                    .addGap(147, 147, 147)
                                    .addComponent(TxtValorEstoque1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LblQuantidadeEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TxtQuantidadeEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnLimparCamposEstoque3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(BtnInserirEstoque)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnDeletarEstoque)
                        .addGap(18, 18, 18)
                        .addComponent(BtnAtualizarEstoque2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(BtnAnteriorEstoque)
                        .addGap(33, 33, 33)
                        .addComponent(BtnProximoEstoque)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(LblTabelaEstoque)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblProdutoEstoque)
                    .addComponent(TxtProdutoEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblQuantidadeEstoque)
                    .addComponent(TxtQuantidadeEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblValorEstoque)
                    .addComponent(TxtValorEstoque1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(BtnLimparCamposEstoque3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnInserirEstoque)
                    .addComponent(BtnDeletarEstoque)
                    .addComponent(BtnAtualizarEstoque2))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAnteriorEstoque)
                    .addComponent(BtnProximoEstoque))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAnteriorEstoque;
    private javax.swing.JButton BtnAtualizarEstoque2;
    private javax.swing.JButton BtnDeletarEstoque;
    private javax.swing.JButton BtnInserirEstoque;
    private javax.swing.JButton BtnLimparCamposEstoque3;
    private javax.swing.JButton BtnProximoEstoque;
    private javax.swing.JLabel LblProdutoEstoque;
    private javax.swing.JLabel LblQuantidadeEstoque;
    private javax.swing.JLabel LblTabelaEstoque;
    private javax.swing.JLabel LblValorEstoque;
    private javax.swing.JTextField TxtProdutoEstoque;
    private javax.swing.JTextField TxtQuantidadeEstoque;
    private javax.swing.JTextField TxtValorEstoque1;
    // End of variables declaration//GEN-END:variables
}
