/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 
 */

 import javax.swing.*;
 import java.sql.*;
 
 

public class TabelaVendas extends javax.swing.JFrame {
    
    public Connection conn = null;
    public Statement stmt;
    public ResultSet rs;
    

    /**
     * Creates new form TabelaVendas
     */
    public TabelaVendas() {
        initComponents();
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbtabelaVendas = new javax.swing.JLabel();
        LbValorTabelaValor = new javax.swing.JLabel();
        TxtOrcamentoTabelaVendas = new javax.swing.JTextField();
        LbOrcamentoTabelaValor = new javax.swing.JLabel();
        TxtVendedorTabelaVendas = new javax.swing.JTextField();
        TxtValorTabelaVendas = new javax.swing.JTextField();
        LbVendedorTabelaValor = new javax.swing.JLabel();
        LbProdutoTabelaValor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtProdutoTabelaVendas = new javax.swing.JTextArea();
        BtnLmparCampTabelaVendas = new javax.swing.JButton();
        BtnDeletarTabelaVendas = new javax.swing.JButton();
        BtnIserirTabelaVendas = new javax.swing.JButton();
        BtnAtualizarTabelaVendas = new javax.swing.JButton();
        BtnAnteriorTabelaVendas = new javax.swing.JButton();
        BtnProximoTabelaVendas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Tabela Valor"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        LbtabelaVendas.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        LbtabelaVendas.setText("  TABELA VENDAS");

        LbValorTabelaValor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LbValorTabelaValor.setText(" Valor :");

        TxtOrcamentoTabelaVendas.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TxtOrcamentoTabelaVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtOrcamentoTabelaVendasActionPerformed(evt);
            }
        });

        LbOrcamentoTabelaValor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LbOrcamentoTabelaValor.setText(" Orçamento :");

        TxtValorTabelaVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtValorTabelaVendasActionPerformed(evt);
            }
        });

        LbVendedorTabelaValor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LbVendedorTabelaValor.setText(" Vendedor :");

        LbProdutoTabelaValor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LbProdutoTabelaValor.setText(" Produto :");

        TxtProdutoTabelaVendas.setColumns(20);
        TxtProdutoTabelaVendas.setRows(5);
        jScrollPane1.setViewportView(TxtProdutoTabelaVendas);

        BtnLmparCampTabelaVendas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnLmparCampTabelaVendas.setText("Limpar Campos");
        BtnLmparCampTabelaVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLmparCampTabelaVendasActionPerformed(evt);
            }
        });

        BtnDeletarTabelaVendas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnDeletarTabelaVendas.setText("DELETAR");
        BtnDeletarTabelaVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeletarTabelaVendasActionPerformed(evt);
            }
        });

        BtnIserirTabelaVendas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnIserirTabelaVendas.setText("INSERIR");
        BtnIserirTabelaVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIserirTabelaVendasActionPerformed(evt);
            }
        });

        BtnAtualizarTabelaVendas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnAtualizarTabelaVendas.setText("ATUALIZAR");
        BtnAtualizarTabelaVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtualizarTabelaVendasActionPerformed(evt);
            }
        });

        BtnAnteriorTabelaVendas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnAnteriorTabelaVendas.setText("Anterior");
        BtnAnteriorTabelaVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnteriorTabelaVendasActionPerformed(evt);
            }
        });

        BtnProximoTabelaVendas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnProximoTabelaVendas.setText("Próximo");
        BtnProximoTabelaVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProximoTabelaVendasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtnIserirTabelaVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnDeletarTabelaVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnAtualizarTabelaVendas)
                .addGap(98, 98, 98))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(LbtabelaVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnLmparCampTabelaVendas)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LbVendedorTabelaValor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LbProdutoTabelaValor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LbOrcamentoTabelaValor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LbValorTabelaValor, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtValorTabelaVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtVendedorTabelaVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtOrcamentoTabelaVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(BtnAnteriorTabelaVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnProximoTabelaVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(LbtabelaVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtValorTabelaVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbValorTabelaValor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbOrcamentoTabelaValor)
                    .addComponent(TxtOrcamentoTabelaVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtVendedorTabelaVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbVendedorTabelaValor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LbProdutoTabelaValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnLmparCampTabelaVendas))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnIserirTabelaVendas)
                    .addComponent(BtnDeletarTabelaVendas)
                    .addComponent(BtnAtualizarTabelaVendas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAnteriorTabelaVendas)
                    .addComponent(BtnProximoTabelaVendas))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnIserirTabelaVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIserirTabelaVendasActionPerformed
       
        try {
             Class.forName("com.mysql.jdbc.Driver");
             conn = DriverManager.getConnection("jdbc:mysql://localhost/petshop",
             "root","123");
       stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
       ResultSet.CONCUR_UPDATABLE);
           String sql;
           sql = "INSERT INTO  vendas VALUES('"
                   + TxtValorTabelaVendas.getText()+ "','"
                    + TxtOrcamentoTabelaVendas.getText()+ "','"
                    + TxtVendedorTabelaVendas.getText() + "','"
                    + TxtProdutoTabelaVendas.getText() + "')";
             
        JOptionPane.showMessageDialog(null, sql);
      int i = 0;
      i = stmt.executeUpdate(sql);
      stmt.close();
      if (i > 0) {
     JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
     //abreTabela();
  }
  }  catch (ClassNotFoundException e) {
     System.out.println(e);
  }    catch (SQLException e) {
     System.out.println(e);
  }
        
        
        
        
        
      
        
    }//GEN-LAST:event_BtnIserirTabelaVendasActionPerformed

    public void atualiza_campos() {
     try {
          TxtValorTabelaVendas.setText("" + rs.getString("Valor"));
          TxtOrcamentoTabelaVendas.setText("" + rs.getString("Orcamento"));
          TxtVendedorTabelaVendas.setText("" + rs.getString("Vendedor"));
          TxtProdutoTabelaVendas.setText("" + rs.getString("Produto"));
    } catch (SQLException e) {
      System.out.println(e);
    }
    }
    
    
   public void AbrTabela(){
       
        String query1 = "Select * from vendas";
   try {
         Class.forName("com.mysql.jdbc.Driver");
conn = DriverManager.getConnection("jdbc:mysql://localhost/petshop",
"root", "123");
stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
ResultSet.CONCUR_READ_ONLY);
rs = stmt.executeQuery(query1);
rs.first();
atualiza_campos();

} catch (ClassNotFoundException e) {
System.out.println(e);
} catch (SQLException e) {
System.out.println(e);
}
       
    }
   
   
    
    
    
    
    private void BtnAtualizarTabelaVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtualizarTabelaVendasActionPerformed

    String query1 = "UPDATE vendas SET Valor =";
    String a = TxtValorTabelaVendas.getText();

  try {
  Class.forName("com.mysql.jdbc.Driver");
  conn = DriverManager.getConnection("jdbc:mysql://localhost/petshop", "root", "123");
  stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
  ResultSet.CONCUR_UPDATABLE);

  String sql = query1 + "'" + TxtValorTabelaVendas.getText()+ "',"
+ "Orcamento='" + TxtOrcamentoTabelaVendas.getText() + "',"
+ "Vendedor='" + TxtVendedorTabelaVendas.getText()
+ "Produto='" + TxtProdutoTabelaVendas.getText()
+ "' Where Valor=" + "'" + TxtValorTabelaVendas.getText() + "'";
JOptionPane.showMessageDialog(null, sql);
int i = 0;
i = stmt.executeUpdate(sql);//executando o comando sql
int y = 0;
stmt.close();
y = stmt.CLOSE_CURRENT_RESULT;
if (i > 0) {
JOptionPane.showMessageDialog(null, "Valores Alterados com sucesso!");
//abreTabela();
}
} catch (ClassNotFoundException e) {
System.out.println(e);
} catch (SQLException e) {
System.out.println(e);
}
        
        
        
    }//GEN-LAST:event_BtnAtualizarTabelaVendasActionPerformed

    private void BtnDeletarTabelaVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeletarTabelaVendasActionPerformed
        
        String query1 = "DELETE FROM vendas WHERE(Valor=";
          String a = TxtValorTabelaVendas.getText();
        try {
             Class.forName("com.mysql.jdbc.Driver");
             conn = DriverManager.getConnection("jdbc:mysql://localhost/petshop",
"root", "123");
             stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
ResultSet.CONCUR_UPDATABLE);
String sql = query1 + "'" + TxtValorTabelaVendas.getText() + "')";
JOptionPane.showMessageDialog(null, sql);
int i = 0;
i = stmt.executeUpdate(sql);//executando o comando sql
stmt.close();
if (i > 0) {
JOptionPane.showMessageDialog(null, "Valores deletados com sucesso!");
// limpando campos
TxtValorTabelaVendas.setText("");
TxtOrcamentoTabelaVendas.setText("");
TxtVendedorTabelaVendas.setText("");
TxtProdutoTabelaVendas.setText("");
//abreTabela();
}
} catch (ClassNotFoundException e) {
System.out.println(e);
} catch (SQLException e) {
System.out.println(e);
}
        
        
        
    }//GEN-LAST:event_BtnDeletarTabelaVendasActionPerformed

    private void BtnLmparCampTabelaVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLmparCampTabelaVendasActionPerformed
        
        
        TxtValorTabelaVendas.setText("");
        TxtOrcamentoTabelaVendas.setText("");
        TxtVendedorTabelaVendas.setText("");
        TxtProdutoTabelaVendas.setText("");
        
        
        
    }//GEN-LAST:event_BtnLmparCampTabelaVendasActionPerformed

    private void BtnAnteriorTabelaVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnteriorTabelaVendasActionPerformed
        
        try {
             rs.previous();
             atualiza_campos();
            } catch (SQLException e) {
             System.out.println(e);
                                     }
        
    }//GEN-LAST:event_BtnAnteriorTabelaVendasActionPerformed

    private void BtnProximoTabelaVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProximoTabelaVendasActionPerformed
        
        try {
             rs.next();
             atualiza_campos();
             } catch (SQLException e) {
             System.out.println(e);
                                      }
        
        
    }//GEN-LAST:event_BtnProximoTabelaVendasActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        //abreTabela();
        
    }//GEN-LAST:event_formWindowOpened

    private void TxtValorTabelaVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtValorTabelaVendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtValorTabelaVendasActionPerformed

    private void TxtOrcamentoTabelaVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtOrcamentoTabelaVendasActionPerformed
        
    }//GEN-LAST:event_TxtOrcamentoTabelaVendasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelaVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAnteriorTabelaVendas;
    private javax.swing.JButton BtnAtualizarTabelaVendas;
    private javax.swing.JButton BtnDeletarTabelaVendas;
    private javax.swing.JButton BtnIserirTabelaVendas;
    private javax.swing.JButton BtnLmparCampTabelaVendas;
    private javax.swing.JButton BtnProximoTabelaVendas;
    private javax.swing.JLabel LbOrcamentoTabelaValor;
    private javax.swing.JLabel LbProdutoTabelaValor;
    private javax.swing.JLabel LbValorTabelaValor;
    private javax.swing.JLabel LbVendedorTabelaValor;
    private javax.swing.JLabel LbtabelaVendas;
    private javax.swing.JTextField TxtOrcamentoTabelaVendas;
    private javax.swing.JTextArea TxtProdutoTabelaVendas;
    private javax.swing.JTextField TxtValorTabelaVendas;
    private javax.swing.JTextField TxtVendedorTabelaVendas;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}

